"""Added Successfully

Revision ID: 7dad1f61989f
Revises: 
Create Date: 2022-11-07 07:12:07.348917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dad1f61989f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=15), nullable=False),
    sa.Column('desc', sa.String(length=15), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('current_usr_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_usr_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    # ### end Alembic commands ###
